easy_admin:
    formats:
        date: 'd/m/Y'
        datetime: 'd/m/Y H:i'

    site_name: 'Au Coeur du Lore'

    design:

#        brand_color: '#E64100'
#    assets:
#        favicon: '/img/favicon.ico'

        menu:
            - { entity: 'Lore',label: 'Lore', icon: 'book'}
            - { entity: 'Persona',label: 'Personnages', icon: 'group'}
            - { entity: 'Race',label: 'Races', icon: 'circle'}
            - { entity: 'Faction',label: 'Factions', icon: 'flag'}
            - { entity: 'Area',label: 'Zones', icon: 'map'}
            - { entity: 'Image',label: 'Images', icon: 'image'}
            - { entity: 'TypeImage',label: 'Type images'}


    entities:
        Lore:
            class: App\Entity\Lore
        Persona:
            class: App\Entity\Persona
        Race:
            class: App\Entity\Race
        Faction:
            class: App\Entity\Faction
        Area:
            class: App\Entity\Area
        Image:
            class: App\Entity\Image

        TypeImage:
            class: App\Entity\TypeImage